services:
    garage:
        container_name: garage
        image: dxflrs/garage:v0.8.1
        ports:
            - 3900:3900
            - 3901:3901
            - 3902:3902
        volumes:
            - ./garage.toml:/etc/garage.toml
            - garage-meta:/var/lib/garage/meta:rw
            - garage-data:/var/lib/garage/data:rw
volumes:
    garage-data:
    garage-meta: